### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by adamfoneil** [adamfoneil/Dapper.Entities#1]
This project has low-level abstractions in the root project [Dapper.Entities](https://github.com/adamfoneil/Dapper.Entities/tree/master/Dapper.Entities). This is so platform-specific implementations can be added as new projects within this solution.

I added a [SqlServer](https://github.com/adamfoneil/Dapper.Entities/tree/master/Dapper.Entities.SqlServer) implementation. The point of this issue is to do something similar for PostgreSQL, which I've stubbed out [here](https://github.com/adamfoneil/Dapper.Entities/tree/master/Dapper.Entities.PostgreSQL). So, there are a few key deliverables:

- implement [PostgreSql.DefaultSqlBuilder](https://github.com/adamfoneil/Dapper.Entities/blob/master/Dapper.Entities.PostgreSQL/DefaultSqlBuilder.cs). See the SqlServer [version](https://github.com/adamfoneil/Dapper.Entities/blob/master/Dapper.Entities.SqlServer/DefaultSqlBuilder.cs) as a guide to see my thinking here. Don't feel locked into my approach, but it does need to generate correct SQL.
- implement tests comparable to the [SqlServer tests](https://github.com/adamfoneil/Dapper.Entities/tree/master/Testing/SqlServer). There are really two things being tested:
    - [SQL builder](https://github.com/adamfoneil/Dapper.Entities/blob/master/Testing/SqlServer/SqlBuilder.cs), just to see that correct insert, update, and delete statements are generated for a couple [sample entities](https://github.com/adamfoneil/Dapper.Entities/tree/master/Testing/Models)
    - [Integration](https://github.com/adamfoneil/Dapper.Entities/blob/master/Testing/SqlServer/Integration.cs) to verify that core crud operations work on a local database. I'm doing some very SqlServer-specific things using DacFX. I don't know what's comparable in the Postgres space.

**Comment by traciturpin** [comment]
- To implement PostgreSQL.DefaultSqlBuilder, I refer the SqlServer version as a guide.
Instead, replace the query syntax from MSSQL to PosgreSQL.
e.g. [dbo].[Business] -> public."Business"

**Comment by traciturpin** [comment]
- To implement test case `SQL builder`, just replace the queries with the form of PostreSQL query syntax.

**Comment by traciturpin** [comment]
- Regarding `Integration` test case, need to imitate DacFX. It should be considered.

**Comment by traciturpin** [comment]
Problem:

Both have the same dependency separately, `Dapper.Entities.Abstractions`
- `Dapper.Entities.PostgreSQL`
- `Dapper.Entities.SqlServer`

And when they are added to `Test` project, it conflicts on Dependency due to duplicated dependencies

**Comment by traciturpin** [comment]
PR created [ #3 ]
